version: "3"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - db:/var/lib/postgresql/data
    ports:
    - "5439:5432"

  create:
    build: ./create
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://docker:docker@db/docker
    depends_on:
      - db

  delete:
    build: ./delete
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://docker:docker@db/docker
    depends_on:
      - db

  read:
    build: ./read
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://docker:docker@db/docker
    depends_on:
      - db

  update:
    build: ./update
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://docker:docker@db/docker
    depends_on:
      - db

volumes:
  db:
    driver: local